name: CI
on:
  schedule:
    - cron: "0 7 * * *"
jobs:
  api-verification:
    name: Verification of API entrypoints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - uses: BSFishy/pip-action@v1
        with:
          requirements: requirements.txt
      - run: python main.py
        env:
          SENDGRID_APIKEY: ${{ secrets.SENDGRID_APIKEY }}
          NOTIFICATION_FROM_ADDR: ${{ secrets.NOTIFICATION_FROM_ADDR }}
          NOTIFICATION_FROM_NAME: ${{ secrets.NOTIFICATION_FROM_NAME }}
          NOTIFICATION_TO_ADDRS: ${{ secrets.NOTIFICATION_TO_ADDRS }}
